name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to IEJL! Thanks for creating your first issue.  Please be specific in your description.  Each bug or feature request should be documented in its own issue.'
        pr-message: 'Thanks so much for creating your first PR.  Please keep the number of changes to a minimum per PR.  Be sure to specify the what, why, how, and result in your description.'
